// Code generated by go generate; DO NOT EDIT.

package artifact

const (
	Commit = "614f95b40df40f80ff6853832486d029f47157ab"
	SHA256 = "5338d31582d7ff98b3ed951fa2f47fc23f439a9233bdf4ef735bd2f5d61607c0"
)
