// Code generated by go generate; DO NOT EDIT.

package artifact

const (
	Commit = "2ba0f9bb685b5b7b4b39dd957dbcff6337d65050"
	SHA256 = "f97c766e7e86190f071b841bc44ba6383ec33b81b75658dbef6abf2eb226d25c"
)
