// Code generated by go generate; DO NOT EDIT.

package artifact

const (
	Commit = "db8cfab39427da41761267626bdab5c343fdc9ff"
	SHA256 = "0506e32a96bf99a31d3fb3d04478ed6128840d90d8a033f318837875d138a031"
)
