// Code generated by go generate; DO NOT EDIT.

package proto

const (
	EasyTierCommit = "1173835133da90e2dc48ea814ba7eb3d9595821e"
	SchemaSHA256   = "f821fe59e06fb1cd4f76f94d392989ef7b7482dd60ba8575265819521f1cddfa"
)
