// Code generated by go generate; DO NOT EDIT.

package proto

const (
	EasyTierCommit = "591ecc7e6272a3385ecf1b3bf3958a6e91a07ac4"
	SchemaSHA256   = "5cea3fa716b5149264de5242f3b0bfd60c074a5f35b274b3f0363e27029b7622"
)
