// Code generated by go generate; DO NOT EDIT.

package proto

const (
	EasyTierCommit = "614f95b40df40f80ff6853832486d029f47157ab"
	SchemaSHA256   = "4fc7f40eac5d3803ed8afe707f2be1db121a022547f91568955c369212875064"
)
